spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
#    postgresql://user:L3V9UebWO8orz4YOk7u2tsJnnyIilNF6@dpg-d15cpl7fte5s7392m2f0-a/mydb1234
#    postgresql://user:L3V9UebWO8orz4YOk7u2tsJnnyIilNF6@dpg-d15cpl7fte5s7392m2f0-a.oregon-postgres.render.com/mydb1234
#    url: jdbc:postgresql://dpg-d15cpl7fte5s7392m2f0-a.oregon-postgres.render.com/mydb1234
    url: jdbc:postgresql://dpg-d15cpl7fte5s7392m2f0-a/mydb1234
    username: user
    password: L3V9UebWO8orz4YOk7u2tsJnnyIilNF6
#    password: 12345
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres

  logging:
    level:
      org.springframework.security: DEBUG

  server:
    servlet:
      session:
        timeout: 30m
        tracking-modes: cookie
        cookie:
          name: JSESSIONID
          http-only: true
          secure: false
          max-age: 1800

